sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install tox-travis codecov flake8
script:
  - tox
  - flake8 s4 tests
  - pip install .
  - test -n "$(s4 version)"
after_success:
  - codecov
cache: pip
