#! /usr/bin/env python

import os

import s3backup


def main():
    target_folder = os.path.expanduser('~/Notebooks')
    bucket = 'michaelaquilina.data2'
    prefix = 'ZimNoteBooks2'

    s3backup.sync(target_folder, bucket, prefix)


if __name__ == '__main__':
    main()
