#! /usr/bin/env python

import os
import json

import boto3

import s3backup
from s3backup.clients import local, s3


def main():

    config_path = os.path.expanduser('~/.config/s3backup/sync.conf')
    if not os.path.exists(config_path):
        raise ValueError('Expected Config file:', config_path)

    with open(config_path, 'r') as fp:
        config = json.load(fp)

    client = boto3.client('s3')
    bucket = config['bucket']

    for target_folder, prefix in config['directories'].items():
        local_client = local.LocalSyncClient(target_folder)
        s3_client = s3.S3SyncClient(client, bucket, prefix)

        print('Syncing', target_folder, 'with', os.path.join(bucket, prefix))
        s3backup.sync(local_client, s3_client)

if __name__ == '__main__':
    main()
