version: 2

test: &test
  steps:
    - checkout
    - run:
        name: install less pager dependency
        command: apt-get update && apt-get install -y less
    - run:
        name: install poetry
        command: pip install poetry
    - run:
        name: install python dependencies
        command: poetry install
    - run:
        name: run pytest
        command: |
          mkdir -p /tmp/test-results
          PYTHONPATH="." poetry run pytest --cov=s4 --cov=tests --cov-report xml --junitxml=/tmp/test-results/pytest-results.xml
          bash <(curl -s https://codecov.io/bash)

    - store_test_results:
        path: /tmp/test-results


jobs:
  lint:
    docker:
      - image: "python:3.7-stretch"
    steps:
      - checkout
      - run:
          name: run linter
          command: |
            pip install flake8
            flake8 s4 tests

      - run:
          name: check isort ordering
          command: |
            pip install isort
            isort s4 tests --diff

      - run:
          name: check black formatting
          command: |
            pip install black
            black s4 tests --check --py36

      - run:
          name: install poetry
          command: pip install poetry

      - run:
          name: version lint
          command: |
            poetry install --no-dev
            CLIENT_VERSION="$(poetry run s4 version)"
            GIT_VERSION="$(git tag --sort "v:refname" | tail -1)"
            PYPROJECT_VERSION="$(grep version pyproject.toml | cut -d" " -f 3)"
            PYPROJECT_VERSION="${PYPROJECT_VERSION//\"/}"

            echo "$CLIENT_VERSION $GIT_VERSION $PYPROJECT_VERSION"
            test "$CLIENT_VERSION" = "$GIT_VERSION"
            test "$CLIENT_VERSION" = "$PYPROJECT_VERSION"
            grep "$CLIENT_VERSION" CHANGELOG.rst

  test-3.7:
    docker:
      - image: "python:3.7-stretch"
    <<: *test

  test-3.6:
    docker:
      - image: "python:3.6-stretch"
    <<: *test

workflows:
  version: 2
  monthly_test:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
              - master
    jobs:
      - lint
      - test-3.6
      - test-3.7

  s4_test:
    jobs:
      - lint
      - test-3.6
      - test-3.7
